apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.secretName }}
data:
  AWS_ACCESS_KEY_ID: {{ .Values.auth.accessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.auth.secretAccessKey | b64enc }}