apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "valid8or-plugin-aws.fullname" . }}-manager-role
  labels:
  {{- include "valid8or-plugin-aws.labels" . | nindent 4 }}
rules:
- apiGroups:
  - validation.spectrocloud.labs
  resources:
  - awsvalidators
  - validationresults
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - validation.spectrocloud.labs
  resources:
  - awsvalidators/finalizers
  verbs:
  - update
- apiGroups:
  - validation.spectrocloud.labs
  resources:
  - awsvalidators/status
  - validationresults/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "valid8or-plugin-aws.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: valid8or-plugin-aws
    app.kubernetes.io/part-of: valid8or-plugin-aws
  {{- include "valid8or-plugin-aws.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "valid8or-plugin-aws.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "valid8or-plugin-aws.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'