{{- if and .Values.auth.secret .Values.auth.secret.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.secret.secretName }}
stringData:
  credentials: |
    [default]
    aws_access_key_id={{ .Values.auth.secret.accessKeyId }}
    aws_secret_access_key={{ .Values.auth.secret.secretAccessKey }}
    {{- if .Values.auth.secret.sessionToken }}
    aws_session_token={{ $.Values.auth.secret.sessionToken }}
    {{- end }}
{{- end }}