apiVersion: validation.spectrocloud.labs/v1alpha1
kind: AwsValidator
metadata:
  name: awsvalidator-sample-iam-fail
spec:
  auth:
    secretName: aws-creds
  iamRules:
  - iamPolicies:
    - name: Failing Policy
      statements:
      - actions:
        - "cognito-sync:ListDatasets"
        effect: Allow
        resources:
        - "*"
      - actions:
        - "iam:PassRole"
        condition:
          type: StringEquals
          key: "iam:PassedToService"
          values:
          - fake.amazonaws.com
        effect: Allow
        resources:
        - "*"
      version: "2012-10-17"
    iamRole: SpectroCloudRole
