apiVersion: validation.spectrocloud.labs/v1alpha1
kind: AwsValidator
metadata:
  name: awsvalidator-sample-iam-policy
spec:
  auth:
    secretName: aws-creds
  defaultRegion: us-west-1
  iamPolicyRules:
  - iamPolicies:
    - name: control-plane.cluster-api-provider-aws.sigs.k8s.io
      statements:
      - actions:
        - "ec2:DescribeInstances"
        effect: Allow
        resources:
        - "*"
      version: "2012-10-17"
    iamPolicyArn: "arn:aws:iam::745150053801:policy/control-plane.cluster-api-provider-aws.sigs.k8s.io"
