apiVersion: validation.spectrocloud.labs/v1alpha1
kind: AwsValidator
metadata:
  name: awsvalidator-sample-tags
spec:
  auth:
    secretName: aws-creds
  defaultRegion: us-west-1
  tagRules:
  - key: "kubernetes.io/role/elb"
    expectedValue: "1"
    region: us-east-2
    resourceType: subnet
    arns:
    - "<arn_1>"
    - "<arn_2>"
